name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Remplacez par votre branche principale si différente
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # Le dossier de sortie de votre build, généralement 'dist' pour Vite
          branch: gh-pages  # La branche où déployer
          clean: true  # Nettoie les anciens fichiers
